### ISSUE TITLE
关于AppLoginProviderBak

### ISSUE THREAD

**Issue by whyalwaysmea** [marshuo/MultiUserLogin#1]
我看还定义了一个AppLoginProviderBak， 这个是废弃的吗？ 如果要用这个应该怎么用呢？

**Comment by marshuo** [comment]
这个类是测试用的，用户名和密码都在写死在代码里面了。
如果你要用的话，修改SecurityConfig.java文件的configure方法，
        // 第二种登录身份认证
        auth.authenticationProvider(new AppLoginProviderBak());

        // auth.authenticationProvider(getAppLoginProvider());

**Comment by whyalwaysmea** [comment]
那是如何和AppUserDetailService进行关联上的呢？

**Comment by marshuo** [comment]
关联AppLoginProvider和AppUserDetailService的代码，在SecurityConfig.java文件getAppLoginProvider()里面。

**Comment by whyalwaysmea** [comment]
> 这个类是测试用的，用户名和密码都在写死在代码里面了。 如果你要用的话，修改SecurityConfig.java文件的configure方法， // 第二种登录身份认证 auth.authenticationProvider(new AppLoginProviderBak());
> 
> ```
>     // auth.authenticationProvider(getAppLoginProvider());
> ```

我是想问以刚说的第二种登录身份认证方式
如果直接修改SecurityConfig.java文件的configure方法，
```java
auth.authenticationProvider(getAppLoginProvider()); 
```
AppLoginProviderBak是怎么和AppUserDetailService关联的呢？

**Comment by whyalwaysmea** [comment]
如果AppLoginProviderBak要走数据库去查用户的话，而不是现在写死的情况

**Comment by whyalwaysmea** [comment]
```java
auth.authenticationProvider(new AppLoginProviderBak()).userDetailsService(appUserDetailService);
```
我知道了，完整的应该是这样的， 谢谢了

**Comment by marshuo** [comment]
不要用AppLoginProviderBak，这个类不支持走数据库验证。
如果要进行数据库验证，provider建议是继承DaoAuthenticationProvider。

你这样写，估计appUserDetailService里面的loadUserByUsername不会被调用。
你可以尝试一下。

**Comment by whyalwaysmea** [comment]
好的，谢谢。我再多试试看

**Comment by whyalwaysmea** [comment]
我用你的代码测试了一下， 通过/appLogin接口进行登录，会依次通过AppUserDetailService和UserDetailsServiceImpl。现在的代码中都是从同一张表里查的用户
如果设计两张表一张app_user，一张sys_user。 那么好像就会有问题。用户登录的时候，在AppUserDetailService中可以从app_user查找到用户，又进入UserDetailsServiceImpl中去查找sys_user表了

**Comment by whyalwaysmea** [comment]
我用你的代码测试了一下， 通过/appLogin接口进行登录，会依次通过AppUserDetailService和UserDetailsServiceImpl。
两张表一张app_user，一张sys_user。如果用户只存在于app_user，那么在UserDetailsServiceImpl中会去查sys_user表，就会报错。这种情况该怎么处理呢？

**Comment by marshuo** [comment]
测试了多次，未能重现你反馈的问题。
建议你重新找个目录，用git clone下载项目代码，运行试试。

**Comment by whyalwaysmea** [comment]
谢谢，我重新测试了一下。 如果/appLogin的密码错误，那么会进入UserDetailsServiceImpl。
请问如果想做app短信登录，不再校验密码了，这里应该怎么改呢？

**Comment by marshuo** [comment]
明白了，/appLogin在密码错误的时候流程有问题。

短信登录这块我不熟，抱歉，帮不到你。

**Comment by whyalwaysmea** [comment]
嗯，谢谢。你的代码对我也有很大帮助
我刚刚试了一下，短信登录只用重写AppLoginProvider里的authenticate就可以了，在这个里面进行用户查找验证就可以，就不用密码校验了。

**Comment by marshuo** [comment]
不客气，能对你有帮助就好。
同样感谢你帮我发现一个bug，需要好好想想怎么解决。

**Comment by marshuo** [comment]
该问题在最新版本已修复
